image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 10

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm install

build_script:
  - npm run dist

test: off
